import {
  Customer,
  Lead,
  LeadContact,
  LeadVehicleInterest,
  Opportunity,
  SellerReminder,
  User,
  Vehicle,
} from '@prisma/client';
import { decimalToString } from '../../common/utils/decimal.util';
import { buildWhatsAppLink } from '../../common/utils/whatsapp.util';
import { ContactChannel } from '@prisma/client';

type SellerSummary = Pick<User, 'id' | 'name' | 'email'> | null;

type CustomerSummary = Pick<Customer, 'id' | 'name' | 'document' | 'phone'> | null;

type VehicleSummary = Pick<
  Vehicle,
  'id' | 'brand' | 'model' | 'licensePlate' | 'status'
> | null;

type LeadWithRelations = Lead & {
  seller?: SellerSummary;
  customer?: CustomerSummary;
  contacts?: LeadContactWithUser[];
  interests?: LeadInterestWithVehicle[];
};

type LeadContactWithUser = LeadContact & {
  user?: Pick<User, 'id' | 'name' | 'email'> | null;
};

type LeadInterestWithVehicle = LeadVehicleInterest & {
  vehicle?: VehicleSummary;
};

type OpportunityWithRelations = Opportunity & {
  seller?: SellerSummary;
  customer?: CustomerSummary;
  vehicle?: VehicleSummary;
};

type LeadContactContext = {
  leadPhone?: string | null;
};

export function toLeadResponse(lead: LeadWithRelations) {
  return {
    id: lead.id,
    tenantId: lead.tenantId,
    name: lead.name,
    phone: lead.phone,
    email: lead.email,
    source: lead.source,
    status: lead.status,
    sellerId: lead.sellerId,
    seller: lead.seller ?? null,
    customerId: lead.customerId,
    customer: lead.customer ?? null,
    expectedAmount: decimalToString(lead.expectedAmount),
    notes: lead.notes,
    nextFollowUpAt: lead.nextFollowUpAt,
    createdAt: lead.createdAt,
    updatedAt: lead.updatedAt,
    createdById: lead.createdById,
  };
}

export function toLeadDetailResponse(lead: LeadWithRelations) {
  return {
    ...toLeadResponse(lead),
    contacts: (lead.contacts ?? []).map((contact) =>
      toLeadContactResponse(contact, { leadPhone: lead.phone }),
    ),
    interests: (lead.interests ?? []).map(toLeadVehicleInterestResponse),
  };
}

export function toLeadContactResponse(
  contact: LeadContactWithUser,
  context?: LeadContactContext,
) {
  const whatsappLink =
    contact.channel === ContactChannel.WHATSAPP
      ? buildWhatsAppLink(context?.leadPhone)
      : null;

  return {
    id: contact.id,
    tenantId: contact.tenantId,
    leadId: contact.leadId,
    channel: contact.channel,
    summary: contact.summary,
    contactedAt: contact.contactedAt,
    userId: contact.userId,
    user: contact.user ?? null,
    metadata: contact.metadata,
    createdAt: contact.createdAt,
    ...(whatsappLink ? { whatsappLink } : {}),
  };
}

export function toLeadVehicleInterestResponse(interest: LeadInterestWithVehicle) {
  return {
    id: interest.id,
    tenantId: interest.tenantId,
    leadId: interest.leadId,
    vehicleId: interest.vehicleId,
    vehicle: interest.vehicle ?? null,
    notes: interest.notes,
    createdAt: interest.createdAt,
  };
}

export function toOpportunityResponse(opportunity: OpportunityWithRelations) {
  return {
    id: opportunity.id,
    tenantId: opportunity.tenantId,
    customerId: opportunity.customerId,
    customer: opportunity.customer ?? null,
    sellerId: opportunity.sellerId,
    seller: opportunity.seller ?? null,
    vehicleId: opportunity.vehicleId,
    vehicle: opportunity.vehicle ?? null,
    title: opportunity.title,
    amount: decimalToString(opportunity.amount),
    status: opportunity.status,
    notes: opportunity.notes,
    nextFollowUpAt: opportunity.nextFollowUpAt,
    createdAt: opportunity.createdAt,
    updatedAt: opportunity.updatedAt,
  };
}

export function toSellerReminderResponse(reminder: SellerReminder) {
  return {
    id: reminder.id,
    tenantId: reminder.tenantId,
    userId: reminder.userId,
    title: reminder.title,
    description: reminder.description,
    dueAt: reminder.dueAt,
    status: reminder.status,
    leadId: reminder.leadId,
    opportunityId: reminder.opportunityId,
    vehicleId: reminder.vehicleId,
    autoGenerated: reminder.autoGenerated,
    completedAt: reminder.completedAt,
    createdAt: reminder.createdAt,
  };
}

export function toFunnelResponse(
  leadCounts: Record<string, number>,
  opportunityCounts: Record<string, number>,
) {
  return {
    leads: leadCounts,
    opportunities: opportunityCounts,
  };
}
